# Generated by Django 4.1 on 2022-08-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
