# Generated by Django 4.1 on 2022-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_rename_total_price_cart_total_price_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
