# Generated by Django 4.1 on 2022-08-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_order_date_created_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.ManyToManyField(blank=True, related_name='orders', to='basket.cart'),
        ),
    ]
